/*
  Simple program to help with running librespot and handling audio.
  What it does :
  - Display a simple background image (containing usage instructions)
  - Start librespot program with a pipe to handle audio data
  - Feed the audio data to SDL audio component
  - Stop librespot program when exiting

  Many thanks to the librespot-org project: https://github.com/librespot-org/librespot
*/

#include <stdlib.h>
#include <stdio.h>
#include <time.h>

#ifdef __EMSCRIPTEN__
#include <emscripten/emscripten.h>
#endif

#include "SDL.h"

#define WINDOW_WIDTH    640
#define WINDOW_HEIGHT   480

#define AUDIO_SAMPLES   4096

// Disable this flag when publishing to steamlink
//#define TEST_MODE

static SDL_Texture *sprite;
static int sprite_w, sprite_h;

SDL_Renderer *renderer;
int done;

// variable declarations
static FILE *audio_buf; // global pointer to the audio buffer to be played

/* Call this instead of exit(), so we can clean up SDL: atexit() is evil. */
static void
quit(int rc)
{
    exit(rc);
}

int
LoadSprite(char *file, SDL_Renderer *renderer)
{
    SDL_Surface *temp;

    /* Load the sprite image */
    temp = SDL_LoadBMP(file);
    if (temp == NULL) {
        SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "Couldn't load %s: %s\n", file, SDL_GetError());
        return (-1);
    }
    sprite_w = temp->w;
    sprite_h = temp->h;

    /* Create textures from the image */
    sprite = SDL_CreateTextureFromSurface(renderer, temp);
    if (!sprite) {
        SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "Couldn't create texture: %s\n", SDL_GetError());
        SDL_FreeSurface(temp);
        return (-1);
    }
    SDL_FreeSurface(temp);

    /* We're ready to roll. :) */
    return (0);
}

// Render a sprite in position (0, 0) on a black screen
void
renderBackground(SDL_Renderer * renderer, SDL_Texture * sprite)
{
    /* Draw a dark background */
    SDL_SetRenderDrawColor(renderer, 0x00, 0x00, 0x00, 0xFF);
    SDL_RenderClear(renderer);

    SDL_Rect *position = malloc(sizeof(SDL_Rect));
    position->x = 0;
    position->y = 0;
    position->w = sprite_w;
    position->h = sprite_h;

    /* Blit the sprite onto the screen */
    SDL_RenderCopy(renderer, sprite, NULL, position);

    /* Update the screen! */
    SDL_RenderPresent(renderer);
}

// audio callback function
// Read fifo generated by spotify and add it to the audio queue
void my_audio_callback(void *userdata, Uint8 *dest_stream, int len) {
    Sint16 *stream = (Sint16 *)dest_stream;
    int actual_samples_read = fread(stream, sizeof(Uint8), len, audio_buf);
    if (actual_samples_read < len) {
        int i;
        for (i=actual_samples_read; i<len; i++) {
            dest_stream[i] = 0;
        }
    }
}

void loop()
{
    SDL_Event event;

    /* Check for events */
    while (SDL_PollEvent(&event)) {
        switch (event.type) {
        case SDL_CONTROLLERDEVICEADDED:
            SDL_GameControllerOpen(event.cdevice.which);
            break;
        case SDL_CONTROLLERBUTTONDOWN:
        case SDL_KEYDOWN:
        case SDL_QUIT:
            done = 1;
            break;
        }
    }

    renderBackground(renderer, sprite);

#ifdef __EMSCRIPTEN__
    if (done) {
        emscripten_cancel_main_loop();
    }
#endif
}

// Init audio device and audio spec + start playing
void initAudio() {
    // Initialize SDL.
	if (SDL_Init(SDL_INIT_AUDIO) < 0)
			return 1;

	static SDL_AudioSpec want; // the specs of our piece of music
	SDL_memset(&want, 0, sizeof(want));
	want.freq = 44100;
	want.format = AUDIO_S16;
	want.channels = 2;
	want.samples = AUDIO_SAMPLES;
	// set the callback function
	want.callback = my_audio_callback;
	//want.callback = NULL;
	want.userdata = NULL;
	/* Open the audio device */
	if ( SDL_OpenAudio(&want, NULL) < 0 ){
	  SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "Couldn't open audio: %s\n", SDL_GetError());
	  exit(-1);
	}

	/* Start playing */
	SDL_PauseAudio(0);
}

// Open audio file buffer
void openAudioBuffer() {

    /* Start librespot and gather std output stream */
#ifdef TEST_MODE
    audio_buf = fopen("sample.bin", "rb");
#else
    // Make sure the env variable "http_proxy" is not set
	unsetenv("http_proxy");
    audio_buf = popen("/home/steam/librespot-org-build/arm-unknown-linux-gnueabihf/release/librespot -v --cache /var/cache --disable-audio-cache --name steamlink --disable-discovery --bitrate 320 --initial-volume 100 --backend pipe 2>/tmp/spotify.log", "r");
#endif // TEST_MODE

	if (audio_buf == NULL){
	  SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "Error starting librespot: %s\n", SDL_GetError());
	  exit(-1);
	}
}

// Close audio file buffer properly
void closeAudioBuffer() {
#ifdef TEST_MODE
    fclose(audio_buf);
#else
	// Send the SIGTERM signal to librespot
	system("pidof /home/steam/librespot-org-build/arm-unknown-linux-gnueabihf/release/librespot | xargs kill");
	// Close the pipe to librespot
	pclose(audio_buf);
#endif // TEST_MODE
}

// Stop the audio device properly
void stopAudio() {
    // shut everything down
	SDL_Delay(100);
	SDL_CloseAudio();
}

int
main(int argc, char *argv[])
{
    SDL_Window *window;

    /* Enable standard application logging */
    SDL_LogSetPriority(SDL_LOG_CATEGORY_APPLICATION, SDL_LOG_PRIORITY_INFO);

    if (SDL_CreateWindowAndRenderer(WINDOW_WIDTH, WINDOW_HEIGHT, 0, &window, &renderer) < 0) {
        quit(2);
    }

    // Load the background image
    if (LoadSprite("spotify2.bmp", renderer) < 0) {
        quit(2);
    }

    SDL_InitSubSystem( SDL_INIT_GAMECONTROLLER );

    openAudioBuffer();
    initAudio();

    /* Main render loop */
    done = 0;

#ifdef __EMSCRIPTEN__
    emscripten_set_main_loop(loop, 0, 1);
#else
    while (!done) {
        loop();
    }
#endif

    stopAudio();
    closeAudioBuffer();

    SDL_QuitSubSystem( SDL_INIT_GAMECONTROLLER );

    quit(0);

    return 0; /* to prevent compiler warning */
}


